alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
rot1 = "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
rot2 = "AJDKSIRUXBLHWTMCQGZNPYFVOE"
rot3 = "BDFHJLCPRTXVZNYEIWGAKMUSQO"
rot4 = "ESOVPZJAYQUIRHXLNFTGKDCMWB"
rot5 = "VZBRGITYUPSDNHLXAWMJQOFECK"
ref = "YRUHQSLDPXNGOKMIEBFZCWVJAT"

